### ISSUE TITLE
Editor - Event object not sending the secret snippet

### ISSUE THREAD

**Issue by caseyokane** [dylan-wright/cs499-intell#15]
Should be a simple fix, just need to go into saveJSON and add an additional check when saving the JSON objects to look for secret snippets and create a description object if so. 

Thx Bray

**Comment by bfullington** [comment]
Resolved.
eventObj now looks like:

`var eventObj = {
            model:"editor.event",
            pk:this.eventKey,

            fields:{
                name: eventName,
                turn: tagTurn
            },

            description:{
                descmodel:'editor.description',
                descpk:this.descKey ++,
                key: isKey,
                secret: false,
                snippet: eventSnip,
                describedby:{
                    descbymodel:'editor.describedby',
                    descbypk:this.descbyKey ++
                }
            },
			
			//add the secret description
			//isSecret is used later to determine if it gets added to the JSON array in submitJSON
			secretDescription:{
				descmodel:'editor.description',
                descpk:this.descKey,
                key: isKey,
                secret: isSecret,
                snippet: secretSnip,
                describedby:{
                    descbymodel:'editor.describedby',
                    descbypk:this.descbyKey
                }
			},

            tags:this.eventTags.slice()


        };
````
